Domain Name: google.ms
Registry Domain ID: 23725-CoCCA
Updated Date: 2021-05-03T09:31:15.538Z
Creation Date: 1999-06-04T12:00:00.0Z
Registry Expiry Date: 2022-06-04T12:00:00.0Z
Registrar Registration Expiration Date: 2022-06-04T12:00:00.0Z
Registrar: MarkMonitor
Registrar Abuse Contact Email: email@markmonitor.com
Registrar Abuse Contact Phone: +1.2083895740
Domain Status: serverUpdateProhibited (Secured by CoCCA Premium Registry Lock) https://icann.org/epp#serverUpdateProhibited (Secured by CoCCA Premium Registry Lock)
Domain Status: serverTransferProhibited (Secured by CoCCA Premium Registry Lock) https://icann.org/epp#serverTransferProhibited (Secured by CoCCA Premium Registry Lock)
Domain Status: serverDeleteProhibited (Secured by CoCCA Premium Registry Lock) https://icann.org/epp#serverDeleteProhibited (Secured by CoCCA Premium Registry Lock)
Domain Status: clientUpdateProhibited https://icann.org/epp#clientUpdateProhibited
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: clientDeleteProhibited https://icann.org/epp#clientDeleteProhibited
Registry Registrant ID: LQP0j-OTvko
Registrant Name: Google, Inc.
Registrant Street: 1600 Amphitheatre Parkway
Registrant Street: Mountain View CA
Registrant City: 94043
Registrant Country: US
Registrant Phone: +1.6502530000
Registrant Fax: +1.6506188571
Registrant Email: email@google.com
Registry Admin ID: I24nt-zjMPH
Admin Name: Google, Inc.
Admin Street: 1600 Amphitheatre Parkway
Admin Street: Mountain View CA
Admin City: 94043
Admin Country: US
Admin Phone: +1.6502530000
Admin Fax: +1.6506188571
Admin Email: email@google.com
Registry Billing ID: Eg1ql-MjQiV
Billing Name: MarkMonitor
Billing Street: 10400 Overland Rd.
Billing Street: PMB 155
Billing City: Boise
Billing State/Province: ID 83709-1433
Billing Country: US
Billing Phone: +1.2083895740
Billing Fax: +1.2083895771
Billing Email: email@markmonitor.com
Name Server: ns1.google.com
Name Server: ns2.google.com
DNSSEC: unsigned
>>> Last update of WHOIS database: 2022-04-07T15:46:05.30Z <<<