Domain:                       google.sk
Registrant:                   Google
Admin Contact:                Google
Tech Contact:                 Google
Registrar:                    FAJN-0002
Created:                      2003-07-24
Updated:                      2018-07-03
Valid Until:                  2019-07-24
Nameserver:                   ns1.google.com
Nameserver:                   ns2.google.com
Nameserver:                   ns3.google.com
Nameserver:                   ns4.google.com
EPP Status:                   ok

Registrar:                    FAJN-0002
Name:                         FAJNOR IP s. r. o.
Organization:                 FAJNOR IP s. r. o.
Organization ID:              46039201
Phone:                        +421.263811927
Email:                        domains@fajnor.sk
Street:                       Krasovského 13
City:                         Bratislava
Postal Code:                  851 01
Country Code:                 SK
Created:                      2017-09-01
Updated:                      2019-04-17

Contact:                      Google
Name:                         Domain Administrator
Organization:                 Google Ireland Holdings Unlimited Company
Phone:                        +353.14361000
Email:                        dns-admin@google.com
Street:                       70 Sir John Rogerson's Quay
City:                         Dublin
Postal Code:                  2
Country Code:                 IE
Registrar:                    FAJN-0002
Created:                      2018-01-26
Updated:                      2018-07-16
