% Request from 80.254.2.190
% This is the Ukrainian Whois query server #F.
% The Whois is subject to Terms of use
% See https://hostmaster.ua/services/
%
% IN THE PROCESS OF DELEGATION OF A DOMAIN NAME,
% THE REGISTRANT IS AN ENTITY WHO USES AND MANAGES A CERTAIN DOMAIN NAME,
% AND THE REGISTRAR IS A BUSINESS ENTITY THAT PROVIDES THE REGISTRANT
% WITH THE SERVICES NECESSARY FOR THE TECHNICAL MAINTENANCE OF THE REGISTRATION AND OPERATION OF THE DOMAIN NAME.
% FOR INFORMATION ABOUT THE REGISTRANT OF THE DOMAIN NAME, YOU SHOULD CONTACT THE REGISTRAR.

domain:           google.com.ua
dom-public:       NO
mnt-by:           ua.markmonitor
nserver:          ns3.google.com
nserver:          ns1.google.com
nserver:          ns4.google.com
nserver:          ns2.google.com
status:           clientDeleteProhibited
status:           clientTransferProhibited
status:           clientUpdateProhibited
created:          2002-12-04 00:00:00+02
modified:         2018-11-02 11:29:08+02
expires:          2019-12-04 00:00:00+02
source:           UAEPP

% Registrar:
% ==========
registrar:        ua.markmonitor
organization:     MarkMonitor Inc.
organization-loc: MarkMonitor Inc.
url:              http://markmonitor.com
city:             Meridian, Idaho
country:          US
abuse-email:      abusecomplaints@markmonitor.com
abuse-postal:     83646 Meridian, Idaho 3540 East Longwing Lane, suite 300
source:           UAEPP

% Registrant:
% ===========
person:           n/a
person-loc:       DNS Admin
organization-loc: Google Inc.
e-mail:           dns-admin@google.com
address:          n/a
address-loc:      1600 Amphitheatre Parkway
address-loc:      CA
address-loc:      Mountain View
postal-code-loc:  94043
country-loc:      US
phone:            +1.6502530000
fax:              +1.6502530001
mnt-by:           ua.markmonitor
status:           ok
status:           linked
created:          2017-07-28 23:53:31+03
source:           UAEPP


% Administrative Contacts:
% =======================
person:           n/a
person-loc:       DNS Admin
organization-loc: Google Inc.
e-mail:           dns-admin@google.com
address:          n/a
address-loc:      1600 Amphitheatre Parkway
address-loc:      CA
address-loc:      Mountain View
postal-code-loc:  94043
country-loc:      US
phone:            +1.6502530000
fax:              +1.6502530001
mnt-by:           ua.markmonitor
status:           ok
status:           linked
created:          2017-07-28 23:53:31+03
source:           UAEPP



% Query time:     5 msec
